/**
 * RegionProps — placement + animation registration for the Phase 7
 * environmental prop sprites generated by `art_sources/generate_props.py`.
 *
 * The brutal audit flagged that the three overworld regions felt like
 * "empty dioramas" — no chickens in the farmland, no boats on the river,
 * no glowing runes in the cosmic chamber. The assets all existed and
 * were registered in `assets.ts`, but no scene actually placed them.
 * This module is the missing wiring.
 *
 * Usage:
 *   placeRegionProps(this, 'prologue');     // call from PrologueScene.create
 *   placeRegionProps(this, 'array_plains'); // call from ArrayPlainsScene.create
 *   placeRegionProps(this, 'twin_rivers');  // call from TwinRiversScene.create
 *
 * Idempotent: safe to call on scene restart (anims are looked up before
 * being re-created; previously-placed sprites are scene-owned and get
 * destroyed by Phaser's normal scene shutdown lifecycle).
 *
 * Position note: y-coords assume world height ~720 (the shared overworld
 * dimension). Props are placed with depth 1-3 so the player sprite (depth
 * ~4) always wins the silhouette war — addresses the visual-hierarchy
 * audit finding that NPCs and props were out-massing the protagonist.
 */

import Phaser from 'phaser';
import { VISUAL_REVAMP_KEYS } from '../config/assets';
import { gameState } from '../core/GameStateManager';

type RegionId = 'prologue' | 'array_plains' | 'twin_rivers';

interface AnimSpec {
  /** Unique anim key (scene-global). Reused across all sprites that play it. */
  key: string;
  /** Number of frames in the sprite sheet. */
  frameCount: number;
  /** Frames per second. */
  frameRate: number;
}

interface HoverSpec {
  /** Pixels of vertical travel each direction. */
  amplitude: number;
  /** Round-trip duration in ms. */
  duration: number;
}

interface DriftSpec {
  /** Pixels of horizontal travel each direction. */
  amplitude: number;
  /** Round-trip duration in ms. */
  duration: number;
}

interface PropPlacement {
  /** Asset key from VISUAL_REVAMP_KEYS. */
  key: string;
  x: number;
  y: number;
  depth: number;
  /** Optional scale (defaults to 1). Pixel-art so usually 1 or 2 exact. */
  scale?: number;
  /** Optional sprite-sheet animation. If absent, prop is a static image. */
  anim?: AnimSpec;
  /** Optional vertical hover tween (e.g. floating orb, dragonfly). */
  hover?: HoverSpec;
  /** Optional horizontal drift tween (e.g. boat bobbing sideways). */
  drift?: DriftSpec;
  /** Optional horizontal flip (use for chickens facing a non-default way). */
  flipX?: boolean;
}

const PLACEMENTS: Record<RegionId, PropPlacement[]> = {
  // ── PROLOGUE — cosmic chamber, world 2400×720 ────────────────────────
  // Runes glow at landmark positions. The chamber is dark + sparse, so
  // these are the small ambient sparks that keep the eye moving.
  prologue: [
    // Tall ancient totems flanking the central hub
    { key: VISUAL_REVAMP_KEYS.PROP_RUNE_TOTEM, x: 760, y: 480, depth: 2 },
    { key: VISUAL_REVAMP_KEYS.PROP_RUNE_TOTEM, x: 1040, y: 480, depth: 2 },
    // Glowing crystal accent on the rune branch (north) and console branch (south)
    {
      key: VISUAL_REVAMP_KEYS.PROP_RUNE_CRYSTAL,
      x: 900, y: 200, depth: 3,
      anim: { key: 'prop-rune-crystal-pulse', frameCount: 4, frameRate: 4 },
    },
    {
      key: VISUAL_REVAMP_KEYS.PROP_RUNE_CRYSTAL,
      x: 900, y: 590, depth: 3,
      anim: { key: 'prop-rune-crystal-pulse', frameCount: 4, frameRate: 4 },
    },
    // Floating orbs that drift slowly — one near each branch
    {
      key: VISUAL_REVAMP_KEYS.PROP_FLOATING_ORB,
      x: 500, y: 260, depth: 5,
      hover: { amplitude: 10, duration: 2400 },
    },
    {
      key: VISUAL_REVAMP_KEYS.PROP_FLOATING_ORB,
      x: 1300, y: 530, depth: 5,
      hover: { amplitude: 12, duration: 2100 },
    },
    // Vertical energy beams flanking the boss gate (east corridor)
    { key: VISUAL_REVAMP_KEYS.PROP_ENERGY_BEAM, x: 1760, y: 380, depth: 1 },
    { key: VISUAL_REVAMP_KEYS.PROP_ENERGY_BEAM, x: 1900, y: 380, depth: 1 },
  ],

  // ── ARRAY PLAINS — farmland, world 1920×720 ──────────────────────────
  // Static farm props + one pecking chicken to make the farmstead feel
  // inhabited instead of being four NPCs on an empty field.
  array_plains: [
    // Chicken pecking near the Sorting Farmer's shed
    {
      key: VISUAL_REVAMP_KEYS.PROP_CHICKEN,
      x: 540, y: 480, depth: 3,
      anim: { key: 'prop-chicken-peck', frameCount: 4, frameRate: 3 },
    },
    // Second chicken farther east, walking in the opposite direction
    {
      key: VISUAL_REVAMP_KEYS.PROP_CHICKEN,
      x: 1240, y: 510, depth: 3,
      anim: { key: 'prop-chicken-peck', frameCount: 4, frameRate: 3 },
      flipX: true,
    },
    // Scarecrow in the centre fields
    { key: VISUAL_REVAMP_KEYS.PROP_SCARECROW, x: 880, y: 520, depth: 2 },
    // Hay bale + tabby cat near the Basket Keeper barn
    { key: VISUAL_REVAMP_KEYS.PROP_HAY_BALE, x: 1380, y: 560, depth: 2 },
    // Watering can sitting in dirt near the Crop Sorter hopper
    { key: VISUAL_REVAMP_KEYS.PROP_WATERING_CAN, x: 1620, y: 540, depth: 2 },
  ],

  // ── TWIN RIVERS — water + bridges, world 1920×720 ───────────────────
  // Drifting boat + dragonflies + lily pads + lantern make the river
  // feel like it's actually flowing instead of being a static texture.
  twin_rivers: [
    // Small boat bobbing on the river
    {
      key: VISUAL_REVAMP_KEYS.PROP_SMALL_BOAT,
      x: 640, y: 470, depth: 2,
      drift: { amplitude: 18, duration: 4200 },
      hover: { amplitude: 3, duration: 1600 },
    },
    // Lily pad clusters in still water
    { key: VISUAL_REVAMP_KEYS.PROP_LILY_PAD_CLUSTER, x: 980, y: 500, depth: 1 },
    { key: VISUAL_REVAMP_KEYS.PROP_LILY_PAD_CLUSTER, x: 1340, y: 460, depth: 1 },
    // Lantern post at each end of the bridge
    {
      key: VISUAL_REVAMP_KEYS.PROP_LANTERN_POST,
      x: 760, y: 340, depth: 3,
      anim: { key: 'prop-lantern-flicker', frameCount: 3, frameRate: 5 },
    },
    {
      key: VISUAL_REVAMP_KEYS.PROP_LANTERN_POST,
      x: 1180, y: 340, depth: 3,
      anim: { key: 'prop-lantern-flicker', frameCount: 3, frameRate: 5 },
    },
    // Dragonflies hovering over the water at varied heights
    {
      key: VISUAL_REVAMP_KEYS.PROP_DRAGONFLY,
      x: 880, y: 420, depth: 5,
      anim: { key: 'prop-dragonfly-wings', frameCount: 2, frameRate: 14 },
      hover: { amplitude: 6, duration: 800 },
    },
    {
      key: VISUAL_REVAMP_KEYS.PROP_DRAGONFLY,
      x: 1480, y: 380, depth: 5,
      anim: { key: 'prop-dragonfly-wings', frameCount: 2, frameRate: 14 },
      hover: { amplitude: 8, duration: 950 },
      flipX: true,
    },
  ],
};

/**
 * Place all region props on the given scene. Idempotent — anims are
 * registered once globally, sprites are recreated on each call (they're
 * scene-owned, so scene shutdown destroys them automatically).
 */
export function placeRegionProps(scene: Phaser.Scene, regionId: RegionId): void {
  const placements = PLACEMENTS[regionId];
  if (!placements) return;

  const reduceMotion = (() => {
    try { return gameState.getSettings().reduceMotion; } catch { return false; }
  })();

  for (const p of placements) {
    let sprite: Phaser.GameObjects.Sprite | Phaser.GameObjects.Image;

    if (p.anim) {
      // Register the anim once per scene if not already present, then play it.
      if (!scene.anims.exists(p.anim.key)) {
        scene.anims.create({
          key: p.anim.key,
          frames: scene.anims.generateFrameNumbers(p.key, {
            start: 0,
            end: p.anim.frameCount - 1,
          }),
          frameRate: p.anim.frameRate,
          repeat: -1,
        });
      }
      sprite = scene.add.sprite(p.x, p.y, p.key);
      if (!reduceMotion) sprite.anims.play(p.anim.key);
    } else {
      sprite = scene.add.image(p.x, p.y, p.key);
    }

    sprite.setDepth(p.depth);
    if (p.scale != null) sprite.setScale(p.scale);
    if (p.flipX) sprite.setFlipX(true);

    // Hover tween (vertical bob) — skip under reduceMotion.
    if (p.hover && !reduceMotion) {
      scene.tweens.add({
        targets: sprite,
        y: p.y - p.hover.amplitude,
        duration: p.hover.duration,
        yoyo: true,
        repeat: -1,
        ease: 'Sine.easeInOut',
        delay: Math.random() * 600,
      });
    }
    // Drift tween (horizontal sway) — skip under reduceMotion.
    if (p.drift && !reduceMotion) {
      scene.tweens.add({
        targets: sprite,
        x: p.x + p.drift.amplitude,
        duration: p.drift.duration,
        yoyo: true,
        repeat: -1,
        ease: 'Sine.easeInOut',
        delay: Math.random() * 800,
      });
    }
  }
}
