/**
 * Movement Gym tileset indices + pure tile-picking logic.
 *
 * The sheet (assets/dev_gym/gym_tileset_v1.png, 8x3 grid of 32px tiles) is
 * generated by codex exec — regenerable via art_sources/generate_gym_tileset.py.
 * Index = row * 8 + col; layout mirrors the generation brief.
 *
 * pickGymTile is pure so the floor plan is unit-testable without Phaser:
 * given a tile coordinate and the room geometry, it returns the frame index
 * to draw there.
 */

export const GYM_TILE = {
  FLOOR_A: 0,
  FLOOR_B: 1,
  FLOOR_SCUFFED: 2,
  FLOOR_CRACKED: 3,
  FLOOR_GRID: 4,
  FLOOR_SPAWN: 5,
  RUNWAY_H: 6,
  RUNWAY_V: 7,
  WALL_TL: 8,
  WALL_TOP: 9,
  WALL_TR: 10,
  WALL_LEFT: 11,
  WALL_RIGHT: 12,
  WALL_BL: 13,
  WALL_BOTTOM: 14,
  WALL_BR: 15,
  BLOCK: 16,
  BLOCK_TOP: 17,
  BLOCK_CRACKED: 18,
  HAZARD: 19,
  PILLAR: 20,
  ARROW_N: 21,
  ARROW_E: 22,
  TARGET_PAD: 23,
} as const;

export interface GymTilePlan {
  /** Room size in tiles. */
  readonly cols: number;
  readonly rows: number;
  /** Spawn point, in tile coords. */
  readonly spawn: { x: number; y: number };
  /** Interior collision blocks, in tile coords (inclusive ranges). */
  readonly blocks: ReadonlyArray<{ x0: number; y0: number; x1: number; y1: number }>;
  /** Horizontal runway strip (one tile row), in tile coords. */
  readonly runway: { y: number; x0: number; x1: number };
}

/** Deterministic per-tile hash for sprinkling floor variants (no RNG). */
function tileHash(tx: number, ty: number): number {
  return (tx * 73856093 + ty * 19349663) % 97;
}

/** Frame index for tile (tx, ty) under the given plan. */
export function pickGymTile(tx: number, ty: number, plan: GymTilePlan): number {
  const maxX = plan.cols - 1;
  const maxY = plan.rows - 1;

  // Perimeter wall ring.
  if (ty === 0) {
    return tx === 0 ? GYM_TILE.WALL_TL : tx === maxX ? GYM_TILE.WALL_TR : GYM_TILE.WALL_TOP;
  }
  if (ty === maxY) {
    return tx === 0 ? GYM_TILE.WALL_BL : tx === maxX ? GYM_TILE.WALL_BR : GYM_TILE.WALL_BOTTOM;
  }
  if (tx === 0) return GYM_TILE.WALL_LEFT;
  if (tx === maxX) return GYM_TILE.WALL_RIGHT;

  // Interior collision blocks: cracked variant sprinkled deterministically.
  for (const b of plan.blocks) {
    if (tx >= b.x0 && tx <= b.x1 && ty >= b.y0 && ty <= b.y1) {
      return tileHash(tx, ty) < 20 ? GYM_TILE.BLOCK_CRACKED : GYM_TILE.BLOCK;
    }
  }

  if (tx === plan.spawn.x && ty === plan.spawn.y) return GYM_TILE.FLOOR_SPAWN;

  if (ty === plan.runway.y && tx >= plan.runway.x0 && tx <= plan.runway.x1) {
    return GYM_TILE.RUNWAY_H;
  }

  // Open floor: checkerboard with sparse deterministic wear.
  const h = tileHash(tx, ty);
  if (h < 4) return GYM_TILE.FLOOR_SCUFFED;
  if (h < 7) return GYM_TILE.FLOOR_CRACKED;
  if (h < 9) return GYM_TILE.FLOOR_GRID;
  return (tx + ty) % 2 === 0 ? GYM_TILE.FLOOR_A : GYM_TILE.FLOOR_B;
}
