/**
 * trialTiles — pure tile plan for the Echo Causeway (the gym pattern:
 * deterministic frame picking, no RNG, unit-testable without Phaser).
 *
 * The sheet (assets/visual_revamp/prologue_trial/tileset_v1.png, 8x3 grid
 * of 32px tiles) is generated by
 * art_sources/generate_prologue_trial_tileset.py. Index = row * 8 + col;
 * layout mirrors the generation script.
 */

export const TRIAL_COLS = 40;
export const TRIAL_ROWS = 23;
export const TRIAL_TILE_PX = 32;

export const TRIAL_TILE = {
  FLOOR_A: 0,
  FLOOR_B: 1,
  FLOOR_ETCHED: 2,
  FLOOR_WORN: 3,
  SPAWN_PAD: 4,
  PILLAR: 5,
  GLYPH_DECOR: 6,
  CRYSTAL: 7,
  RIM_TL: 8,
  RIM_TOP: 9,
  RIM_TR: 10,
  RIM_LEFT: 11,
  RIM_RIGHT: 12,
  RIM_BL: 13,
  RIM_BOTTOM: 14,
  RIM_BR: 15,
  VOID_A: 16,
  VOID_STARS: 17,
  ISLE_TOP: 18,
  ISLE_BOTTOM: 19,
  RUNE_DIM: 20,
  RUNE_LIT: 21,
  RUNE_CRUMBLED: 22,
  BRIDGE: 23,
} as const;

export type TrialBand = "exit" | "chasm" | "islet" | "entry" | "rim";

/** Horizontal band classification for row ty. */
export function bandAt(ty: number): TrialBand {
  if (ty === 0 || ty === TRIAL_ROWS - 1) return "rim";
  if (ty <= 3) return "exit";
  if (ty <= 7) return "chasm";
  if (ty <= 9) return "islet";
  if (ty <= 13) return "chasm";
  if (ty <= 15) return "islet";
  if (ty <= 19) return "chasm";
  return "entry";
}

/** Deterministic per-tile hash for wear/star sprinkling (no RNG). */
function tileHash(tx: number, ty: number): number {
  return (tx * 73856093 + ty * 19349663) % 97;
}

const SPAWN_TILE = { tx: 20, ty: 21 };

/**
 * Frame index for the STATIC layer at (tx, ty). Causeway runes are
 * dynamic Images on top; underneath them lies void.
 */
export function pickTrialTile(tx: number, ty: number): number {
  const maxX = TRIAL_COLS - 1;
  const maxY = TRIAL_ROWS - 1;
  if (ty === 0)
    return tx === 0
      ? TRIAL_TILE.RIM_TL
      : tx === maxX
        ? TRIAL_TILE.RIM_TR
        : TRIAL_TILE.RIM_TOP;
  if (ty === maxY)
    return tx === 0
      ? TRIAL_TILE.RIM_BL
      : tx === maxX
        ? TRIAL_TILE.RIM_BR
        : TRIAL_TILE.RIM_BOTTOM;
  if (tx === 0) return TRIAL_TILE.RIM_LEFT;
  if (tx === maxX) return TRIAL_TILE.RIM_RIGHT;

  const band = bandAt(ty);
  const h = tileHash(tx, ty);

  if (band === "chasm") {
    return h < 18 ? TRIAL_TILE.VOID_STARS : TRIAL_TILE.VOID_A;
  }

  // Stone bands. Islet edges read as ledges over the void.
  if (band === "islet") {
    if (bandAt(ty - 1) === "chasm") return TRIAL_TILE.ISLE_TOP;
    if (bandAt(ty + 1) === "chasm") return TRIAL_TILE.ISLE_BOTTOM;
  }
  if (band === "exit" && bandAt(ty + 1) === "chasm")
    return TRIAL_TILE.ISLE_BOTTOM;
  if (band === "entry" && bandAt(ty - 1) === "chasm")
    return TRIAL_TILE.ISLE_TOP;

  if (tx === SPAWN_TILE.tx && ty === SPAWN_TILE.ty) return TRIAL_TILE.SPAWN_PAD;

  if (h < 5) return TRIAL_TILE.FLOOR_WORN;
  if (h < 9) return TRIAL_TILE.FLOOR_ETCHED;
  if (h < 11) return TRIAL_TILE.GLYPH_DECOR;
  return (tx + ty) % 2 === 0 ? TRIAL_TILE.FLOOR_A : TRIAL_TILE.FLOOR_B;
}
